CREATE TABLE public.railways
(
    railway_id               varchar(50) PRIMARY KEY NOT NULL,
    name                     varchar(50)             NOT NULL,
    abbreviation             varchar(10),
    registered_company_name  varchar(250),
    organization_entity_type varchar(100),
    description_en           varchar(2500),
    description_it           varchar(2500),
    country                  varchar(3)              NOT NULL,
    operating_since          date,
    operating_until          date,
    status                   varchar(100),
    gauge_m                  numeric(19, 5),
    track_gauge              varchar(100),
    headquarters             varchar(250),
    total_length_mi          numeric(19, 5),
    total_length_km          numeric(19, 5),
    contact_email            varchar(255),
    contact_website_url      varchar(100),
    contact_phone            varchar(20),
    socials_facebook         varchar(100),
    socials_instagram        varchar(100),
    socials_linkedin         varchar(100),
    socials_twitter          varchar(100),
    socials_youtube          varchar(100),
    created_date             timestamp               NOT NULL,
    last_modified_date       timestamp               NOT NULL,
    version                  INT                     NOT NULL
);
