package io.github.carlomicieli.catalog.catalogitems;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

import java.util.UUID;

@JsonIgnoreProperties(
    value = "category", // ignore manually set category, it will be automatically generated by Jackson during serialization
    allowSetters = true // allows the category to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "category", visible = true)
@JsonSubTypes({
    @JsonSubTypes.Type(value = ElectricMultipleUnit.class, name = "ElectricMultipleUnit"),
    @JsonSubTypes.Type(value = FreightCar.class, name = "FreightCar"),
    @JsonSubTypes.Type(value = Locomotive.class, name = "Locomotive"),
    @JsonSubTypes.Type(value = PassengerCar.class, name = "PassengerCar"),
    @JsonSubTypes.Type(value = Railcar.class, name = "Railcar")
})
public abstract class RollingStock {
    @JsonProperty("category")
    private RollingStockCategory category;

    @JsonProperty("rolling_stock_id")
    private UUID rollingStockId;

    @JsonProperty("railway")
    private String railway;

    @JsonProperty("epoch")
    private String epoch;

    @JsonProperty("livery")
    private String livery;

    @JsonProperty("length_over_buffers")
    private LengthOverBuffers lengthOverBuffers;

    @JsonProperty("technical_specifications")
    private TechnicalSpecifications technicalSpecifications;
}
