name: Catalog Service CI
on:
  push:
    paths:
      - '.github/workflows/catalog-ci.yml'
      - 'catalog-service/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Print versions
        run: |
            echo "JAVA_HOME: $JAVA_HOME"
            java --version

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.0.1

      - name: Compile the project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: catalog-service:build -x check

      - name: Checks that sourcecode satisfies formatting rules
        uses: gradle/gradle-build-action@v2
        with:
          arguments: catalog-service:spotlessCheck

      - name: Run the unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: catalog-service:test

      - name: Run the integration tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: catalog-service:integrationTest
